name: First workflow
on: push
jobs: 
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello'
  pwd-ls:
    name: PWD , ls
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: pwd
      - name: List files
        run: ls -al
